In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
filePath = '../Data/heart.csv'

data = pd.read_csv(filePath)

data.head(20)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0
10,37,F,NAP,130,211,0,Normal,142,N,0.0,Up,0
11,58,M,ATA,136,164,0,ST,99,Y,2.0,Flat,1
12,39,M,ATA,120,204,0,Normal,145,N,0.0,Up,0
13,49,M,ASY,140,234,0,Normal,140,Y,1.0,Flat,1
14,42,F,NAP,115,211,0,ST,137,N,0.0,Up,0
15,54,F,ATA,120,273,0,Normal,150,N,1.5,Flat,0
16,38,M,ASY,110,196,0,Normal,166,N,0.0,Flat,1
17,43,F,ATA,120,201,0,Normal,165,N,0.0,Up,0
18,60,M,ASY,100,248,0,Normal,125,N,1.0,Flat,1
19,36,M,ATA,120,267,0,Normal,160,N,3.0,Flat,1

In [3]:
print("(Rows, columns): " + str(data.shape))
data.columns

(Rows, columns): (918, 12)

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [4]:
#Unique values for each variable
data.nunique(axis=0)

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [5]:
data.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [6]:
#Check for missing values
print(data.isna().sum())

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [7]:
#Check if there's a good proportion between the outputs
data['HeartDisease'].value_counts()

1    508
0    410
Name: HeartDisease, dtype: int64

In [8]:
#Preprocesing
from sklearn import preprocessing
data_proc = pd.DataFrame()
le = preprocessing.LabelEncoder()
var = ["Age", "Sex", "ChestPainType", "RestingBP", "Cholesterol","FastingBS","RestingECG","MaxHR","ExerciseAngina","Oldpeak","ST_Slope","HeartDisease"]
for v in var:
    #le.fit(data[v])
    data_proc[v] = le.fit_transform(data[v])

data_proc.head(30)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,12,1,1,41,147,0,1,98,0,10,2,0
1,21,0,2,55,40,0,1,82,0,20,1,1
2,9,1,1,31,141,0,2,25,0,10,2,0
3,20,0,0,39,72,0,1,34,1,25,1,1
4,26,1,2,49,53,0,1,48,0,10,2,0
5,11,1,2,22,189,0,1,96,0,10,2,0
6,17,0,1,31,95,0,1,96,0,10,2,0
7,26,1,1,14,66,0,1,68,0,10,2,0
8,9,1,0,41,65,0,1,56,1,25,1,1
9,20,0,1,22,142,0,1,46,0,10,2,0
10,9,0,2,31,69,0,1,68,0,10,2,0
11,30,1,1,37,24,0,2,26,1,30,1,1
12,11,1,1,22,62,0,1,71,0,10,2,0
13,21,1,0,41,92,0,1,66,1,20,1,1
14,14,0,2,18,69,0,2,63,0,10,2,0
15,26,0,1,22,131,0,1,76,0,25,1,0
16,10,1,0,14,54,0,1,92,0,10,1,1
17,15,0,1,22,59,0,1,91,0,10,2,0
18,32,1,0,7,106,0,1,51,0,20,1,1
19,8,1,1,22,125,0,1,86,0,39,1,1
20,15,0,3,7,81,0,1,68,0,10,2,0
21,16,1,1,22,44,0,1,68,0,20,1,0
22,21,0,1,25,59,0,1,90,0,10,2,0
23,16,1,1,49,146,0,1,76,1,39,1,1
24,12,1,2,31,73,0,1,64,0,10,2,0
25,8,1,2,31,67,0,1,104,0,10,2,0
26,25,1,0,25,118,0,2,38,1,39,1,0
27,24,1,1,22,142,0,1,44,0,10,2,0
28,25,0,1,16,216,0,1,53,0,10,2,0
29,23,1,1,26,48,0,1,71,0,10,2,0

In [9]:
#assigning data and outputs to X, Y
X = data_proc.iloc[:, :-1].values
y = data_proc.iloc[:, -1].values

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 1)

In [11]:
#Normalize data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-1.1161998 ,  0.52162923, -0.82452816, ...,  1.23734978,
         1.6923356 , -0.65816623],
       [-0.14954853, -1.91707048,  1.24101337, ..., -0.80817891,
        -0.85540074,  1.04887976],
       [ 1.24672552, -1.91707048, -0.82452816, ..., -0.80817891,
         0.1636938 , -0.65816623],
       ...,
       [ 1.03191413,  0.52162923, -0.82452816, ...,  1.23734978,
         2.91524904,  1.04887976],
       [-1.54582259,  0.52162923,  0.20824261, ...,  1.23734978,
         0.1636938 , -0.65816623],
       [-1.33101119, -1.91707048,  0.20824261, ..., -0.80817891,
        -0.85540074,  1.04887976]])

In [14]:
#Logistic Regression
from sklearn.metrics import classification_report 
from sklearn.linear_model import LogisticRegression

model1 = LogisticRegression(random_state=1,max_iter=500) # get instance of model
model1.fit(x_train, y_train) # Train/Fit model 

y_pred1 = model1.predict(x_test) # get y predictions
print(classification_report(y_test, y_pred1)) # output accuracy

              precision    recall  f1-score   support

           0       0.89      0.88      0.88        74
           1       0.92      0.93      0.92       110

    accuracy                           0.91       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.91      0.91      0.91       184

In [17]:
x_test[2]

array([ 23,   1,   0,  41, 155,   0,   1,  48,   1,  48,   1], dtype=int64)

In [96]:
y_test[95]

1

In [18]:
model1.predict(x_test[2].reshape(1, -1))[0]

1

In [16]:
import joblib
joblib.dump(model1,'LGModel.pkl')

['LGModel.pkl']

In [27]:
temp={}
temp['Age']=56
temp['Sex']=0
temp['ChestPainType']=2
temp['RestingBP']=120
temp['Cholesterol']=170
temp['FastingBS']=80
temp['RestingECG']=1
temp['MaxHR']=156
temp['ExerciseAngina']=0
temp['Oldpeak']=0.0
temp['ST_Slope']=1

In [60]:
testData = np.array([20,0,0,39,72,0,1,34,1,25,1])

In [61]:
model1.predict(testData.reshape(1, -1))[0]

0

In [28]:
testData = pd.DataFrame({'x':temp})

In [31]:
testData.resha

[56, 0, 2, 120, 170, 80, 1, 156, 0, 0.0, 1]

In [13]:
#K-Nearest Neighbors
from sklearn.metrics import classification_report 
from sklearn.neighbors import KNeighborsClassifier

model2 = KNeighborsClassifier() # get instance of model
model2.fit(x_train, y_train) # Train/Fit model 

y_pred2 = model2.predict(x_test) # get y predictions
print(classification_report(y_test, y_pred2)) # output accuracy

              precision    recall  f1-score   support

           0       0.84      0.86      0.85        74
           1       0.91      0.89      0.90       110

    accuracy                           0.88       184
   macro avg       0.87      0.88      0.88       184
weighted avg       0.88      0.88      0.88       184

In [14]:
#SVM
from sklearn.metrics import classification_report 
from sklearn.svm import SVC

model3 = SVC(random_state=1) # get instance of model
model3.fit(x_train, y_train) # Train/Fit model 

y_pred3 = model3.predict(x_test) # get y predictions
print(classification_report(y_test, y_pred3)) # output accuracy

              precision    recall  f1-score   support

           0       0.89      0.88      0.88        74
           1       0.92      0.93      0.92       110

    accuracy                           0.91       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.91      0.91      0.91       184

In [19]:
#Decission Tree
from sklearn.metrics import classification_report 
from sklearn.tree import DecisionTreeClassifier

model5 = DecisionTreeClassifier(random_state=1, criterion='entropy') # get instance of model
model5.fit(x_train, y_train) # Train/Fit model 

y_pred5 = model5.predict(x_test) # get y predictions
print(classification_report(y_test, y_pred5)) # output accuracy

              precision    recall  f1-score   support

           0       0.67      0.84      0.74        74
           1       0.87      0.72      0.79       110

    accuracy                           0.77       184
   macro avg       0.77      0.78      0.76       184
weighted avg       0.79      0.77      0.77       184

In [33]:
#Multi Layer Perceptron
from sklearn.metrics import classification_report 
from sklearn.neural_network import MLPClassifier

model6 = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(4, 2), random_state=1, max_iter=500) # get instance of model
model6.fit(x_train, y_train) # Train/Fit model 

y_pred6 = model6.predict(x_test) # get y predictions
print(classification_report(y_test, y_pred6)) # output accuracy

              precision    recall  f1-score   support

           0       0.84      0.85      0.85        74
           1       0.90      0.89      0.89       110

    accuracy                           0.88       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.88      0.88      0.88       184